[project]
name = "pathmanager"
version = "0.1.0"
description = "A tool for SideFX Houdini to manage file paths."
authors = [
    {name = "Beat Reichenbach"}
]
requires-python = ">=3.10"
license = {text = "MIT"}
readme = "README.md"
dependencies = [
    "qt_parameters>=1.4,<2",
    "qtpy>=2.0,<3",
    "platformdirs>=4.0,<5"
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.0",
    "python-semantic-release>=9.0",
    "pytest>=8.0",
    "qt-material-icons>=0.2,<1",
    "ruff>=0.16",
    "ty>=0.0.82",
    "types-houdini>=21.0",
    "PySide6>=6.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["pathmanager*"]

[tool.setuptools.package-data]
pathmanager = ["py.typed", "**/resources"]

[tool.semantic_release]
allow_zero_version = true
version_variables = ["pathmanager/__init__.py:__version__"]
version_toml  = ["pyproject.toml:project.version"]
build_command = """
    rm -rf build && \
    mkdir -p build/pathmanager/python && \
    cp -r src/python_panels src/*.xml build/pathmanager/ && \
    cp src/*.json build/ && \
    uv pip install . --upgrade --target build/pathmanager/python && \
    rm -rf build/pathmanager/python/bin build/pathmanager/python/*.dist-info build/bdist.* && \
    mkdir -p dist && \
    cd build && zip -r ../dist/pathmanager.zip .
"""

[tool.semantic_release.remote]
ignore_token_for_push = true

[tool.semantic_release.publish]
upload_to_vcs_release = true

[tool.ruff]
extend-exclude = ["pathmanager/qt_material_icons"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP", "B", "SIM", "ANN", "RUF"]
ignore = ["SIM108"]

[tool.ty.src]
exclude = ["pathmanager/qt_material_icons"]

[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli = true
log_level = "INFO"
